spring:
  datasource:
    username: root
    password: realworld123
    url: jdbc:mysql://localhost:3306/realworld?createDatabaseIfNotExist=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  sql:
    init:
      data-locations: classpath:db/*
      platform: mysql
      mode: always

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.aomentec.realworld.pojo

server:
  port: 8080
