spring:
  datasource:
    username: root
    password: realworld123
    url: jdbc:mysql://localhost:3306/realworld?characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  sql:
    init:
      mode: always

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.aomentec.realworld.

server:
  port: 8080

security:
  basic:
    enabled: false
